"""
Fraud Detection Model — Training Script
========================================
Trains a GradientBoostingClassifier with Optuna hyperparameter tuning,
evaluates on the held-out test set, logs everything to MLflow, and
saves the final model to models/fraud_detection/fraud_model_v1.pkl.

Usage
-----
    python models/fraud_detection/train.py

Requirements
------------
    data/raw/loan_applications.parquet       (generated by data/generate_synthetic_data.py)
    data/raw/loan_applications_test.parquet
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path

import joblib
import mlflow
import mlflow.sklearn
import numpy as np
import optuna
import pandas as pd
from scipy.stats import ks_2samp
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.preprocessing import LabelEncoder

# Add project root to path so feature_pipeline is importable
sys.path.insert(0, str(Path(__file__).parents[2]))
from feature_pipeline.features import FeaturePipelineConfig, compute_features  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).parents[2]
DATA_DIR = PROJECT_ROOT / "data" / "raw"
MODEL_DIR = Path(__file__).parent
MODEL_PATH = MODEL_DIR / "fraud_model_v1.pkl"

FEATURE_CONFIG = FeaturePipelineConfig()
FEATURE_COLS = FEATURE_CONFIG.feature_list  # 11 engineered features

# ---------------------------------------------------------------------------
# Fraud flag synthesis
# ---------------------------------------------------------------------------

_FRAUD_WEIGHTS = {
    "high_loan": 2.0,       # loan_amount > 80th percentile
    "low_income": 2.0,      # annual_income < 20th percentile
    "short_employment": 1.5, # employer_tenure_months < 3
    "zero_accounts": 3.0,   # num_open_accounts == 0
    "high_marks": 1.5,      # num_derogatory_marks > 3
}


def synthesize_fraud_flag(df: pd.DataFrame, target_rate: float = 0.03) -> pd.Series:
    """Create a synthetic fraud label using heuristic risk factors.

    Fraud probability is derived from a weighted risk score that rewards
    the co-occurrence of suspicious signals.  The flag is then calibrated
    to approximately *target_rate* overall prevalence.
    """
    rng = np.random.default_rng(7)

    loan_thresh = df["loan_amount"].quantile(0.80)
    income_thresh = df["annual_income"].quantile(0.20)

    score = (
        _FRAUD_WEIGHTS["high_loan"] * (df["loan_amount"] > loan_thresh).astype(float)
        + _FRAUD_WEIGHTS["low_income"] * (df["annual_income"] < income_thresh).astype(float)
        + _FRAUD_WEIGHTS["short_employment"] * (df["employer_tenure_months"] < 3).astype(float)
        + _FRAUD_WEIGHTS["zero_accounts"] * (df["num_open_accounts"] == 0).astype(float)
        + _FRAUD_WEIGHTS["high_marks"] * (df["num_derogatory_marks"] > 3).astype(float)
    )

    # Logistic conversion to probability
    max_score = sum(_FRAUD_WEIGHTS.values())
    prob = 1 / (1 + np.exp(-2.5 * (score / max_score - 0.5)))
    # Calibrate to target rate
    prob = (prob / prob.mean() * target_rate).clip(0, 1)
    return pd.Series((rng.random(len(df)) < prob).astype(int), index=df.index, name="fraud_flag")


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------


def load_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    """Load and feature-engineer train/test DataFrames."""
    logger.info("Loading datasets …")
    df_train = pd.read_parquet(DATA_DIR / "loan_applications.parquet")
    df_test = pd.read_parquet(DATA_DIR / "loan_applications_test.parquet")

    logger.info("Synthesising fraud labels …")
    df_train["fraud_flag"] = synthesize_fraud_flag(df_train)
    df_test["fraud_flag"] = synthesize_fraud_flag(df_test)

    logger.info("Computing engineered features …")
    df_train = compute_features(df_train, FEATURE_CONFIG)
    df_test = compute_features(df_test, FEATURE_CONFIG)

    logger.info("Train: %d rows | Test: %d rows", len(df_train), len(df_test))
    logger.info(
        "Train fraud rate: %.2f%% | Test fraud rate: %.2f%%",
        df_train["fraud_flag"].mean() * 100,
        df_test["fraud_flag"].mean() * 100,
    )
    return df_train, df_test


def _objective(trial: optuna.Trial, X_train, y_train, X_val, y_val) -> float:
    """Optuna objective: maximise F1 score on validation set."""
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 500),
        "max_depth": trial.suggest_int("max_depth", 2, 6),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 10, 100),
        "random_state": 42,
    }
    model = GradientBoostingClassifier(**params)
    model.fit(X_train, y_train)
    preds = model.predict(X_val)
    return f1_score(y_val, preds, zero_division=0)


def train() -> None:
    mlflow.set_experiment("fraud_detection")

    df_train, df_test = load_data()

    X_train = df_train[FEATURE_COLS].values
    y_train = df_train["fraud_flag"].values
    X_test = df_test[FEATURE_COLS].values
    y_test = df_test["fraud_flag"].values

    # Split 10 % of train for Optuna validation
    val_cut = int(len(X_train) * 0.9)
    X_tr, X_val = X_train[:val_cut], X_train[val_cut:]
    y_tr, y_val = y_train[:val_cut], y_train[val_cut:]

    logger.info("Starting Optuna hyperparameter search (10 trials) …")
    optuna.logging.set_verbosity(optuna.logging.WARNING)
    study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42))
    study.optimize(lambda t: _objective(t, X_tr, y_tr, X_val, y_val), n_trials=10)

    best_params = study.best_params
    best_params["random_state"] = 42
    logger.info("Best params: %s", best_params)

    logger.info("Training final model on full train set …")
    final_model = GradientBoostingClassifier(**best_params)
    final_model.fit(X_train, y_train)

    # ── Evaluation ──────────────────────────────────────────────────────────
    y_prob = final_model.predict_proba(X_test)[:, 1]
    y_pred = final_model.predict(X_test)

    precision = precision_score(y_test, y_pred, zero_division=0)
    recall = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    auc = roc_auc_score(y_test, y_prob)

    # KS statistic
    ks_stat, _ = ks_2samp(y_prob[y_test == 1], y_prob[y_test == 0])

    print("\n===  Fraud Detection — Classification Report  ===")
    print(classification_report(y_test, y_pred))
    print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
    print(f"\nPrecision: {precision:.4f}  AUC: {auc:.4f}  KS: {ks_stat:.4f}")

    # Assertions
    assert precision > 0.85, f"Precision {precision:.4f} < 0.85"
    assert auc > 0.80, f"AUC {auc:.4f} < 0.80"
    logger.info("All performance assertions passed.")

    # ── MLflow logging ────────────────────────────────────────────────────
    with mlflow.start_run():
        mlflow.log_params(best_params)
        mlflow.log_metrics(
            {
                "precision": precision,
                "recall": recall,
                "f1": f1,
                "auc": auc,
                "ks_statistic": ks_stat,
            }
        )
        mlflow.sklearn.log_model(final_model, artifact_path="fraud_model")

    # ── Save model ─────────────────────────────────────────────────────────
    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(final_model, MODEL_PATH)
    logger.info("Model saved to %s", MODEL_PATH)


if __name__ == "__main__":
    train()
