"""
Decision Engine
===============
Combines fraud detection, credit risk, and pricing model outputs into a
single, FCRA-compliant loan decision.

Decision Logic (from PRD)
--------------------------
  fraud_flag == "reject"         → REJECT         (AA02)
  fraud_flag == "manual_review"  → MANUAL_REVIEW  (AA05)
  pd_score < 0.05                → APPROVE        (standard / base rate)
  0.05 ≤ pd_score ≤ 0.10        → APPROVE        (risk-priced rate)
  pd_score > 0.10                → REJECT         (AA01)

FCRA Adverse Action Codes
--------------------------
  AA01 — High probability of default
  AA02 — Fraud indicators detected
  AA03 — Insufficient credit history
  AA04 — Debt-to-income ratio too high
  AA05 — Application requires manual review

Public API
----------
>>> from decision_engine.engine import (
...     DecisionRequest, DecisionResult, make_decision, REASON_CODE_DESCRIPTIONS
... )
"""

from __future__ import annotations

import logging
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

log = logging.getLogger(__name__)

# Make project root importable when run as a script
sys.path.insert(0, str(Path(__file__).parents[1]))

from models.pricing.engine import PricingResult  # noqa: E402

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DECISION_APPROVE = "APPROVE"
DECISION_REJECT = "REJECT"
DECISION_MANUAL_REVIEW = "MANUAL_REVIEW"
DECISION_CONDITIONAL = "CONDITIONAL"
#: Conditional approval — terms are stored in DecisionResult.conditional_terms.

#: Mapping of FCRA adverse action codes to their human-readable descriptions.
REASON_CODE_DESCRIPTIONS: Dict[str, str] = {
    "AA01": "High probability of default",
    "AA02": "Fraud indicators detected",
    "AA03": "Insufficient credit history",
    "AA04": "Debt-to-income ratio too high",
    "AA05": "Application requires manual review",
}

# Risk thresholds (mirror models/credit_risk/predict.py)
PD_THRESHOLD_LOW = 0.05    # below → low risk → APPROVE at base rate
PD_THRESHOLD_MEDIUM = 0.10  # 0.05–0.10 → medium risk → APPROVE at priced rate

# ---------------------------------------------------------------------------
# Escalation band helpers (S6-A Task 3)
# ---------------------------------------------------------------------------

def _load_escalation_bands(product_type: str) -> tuple[float, float]:
    """Return (refer_low, refer_high) for *product_type*.

    Resolution order:
    1. ``config/agent_config.yaml`` ``decision_engine.escalation_bands``
    2. Hardcoded fallback (PD_THRESHOLD_LOW, PD_THRESHOLD_MEDIUM).
    """
    try:
        import yaml  # type: ignore
        _cfg_path = Path(__file__).parents[1] / "config" / "agent_config.yaml"
        with open(_cfg_path) as _f:
            _cfg = yaml.safe_load(_f)
        _bands = _cfg.get("decision_engine", {}).get("escalation_bands", [])
        for _band in _bands:
            if _band.get("product") == product_type:
                _lo, _hi = _band["refer_if_pd_between"]
                return float(_lo), float(_hi)
    except Exception:
        pass
    return PD_THRESHOLD_LOW, PD_THRESHOLD_MEDIUM

# Heuristic thresholds for supplemental reason codes
DTI_HIGH_THRESHOLD = 0.43       # DTI above this → AA04
OPEN_ACCOUNTS_MIN = 1           # fewer than this → AA03


# ---------------------------------------------------------------------------
# ConditionalTerms dataclass
# ---------------------------------------------------------------------------


@dataclass
class ConditionalTerms:
    """Terms for a conditional approval decision.

    Populated only when decision == DECISION_CONDITIONAL.
    Generated by the post-decision override workflow (referral resolution),
    not by the automated pipeline.
    """

    max_loan_amount: Optional[float] = None      # USD cap on approval
    required_collateral: Optional[str] = None    # e.g. "vehicle title"
    co_signer_required: bool = False             # True if co-signer required
    rate_premium_pct: Optional[float] = None     # additional rate premium (%)
    additional_conditions: Optional[str] = None  # free-text


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class FraudResult:
    """Fraud model output for a single application.

    Can be constructed directly from a row of the DataFrame returned by
    ``models.fraud_detection.predict.predict_fraud()``.
    """

    fraud_probability: float
    fraud_flag: str  # "continue" | "manual_review" | "reject"


@dataclass
class CreditResult:
    """Credit risk model output for a single application.

    Can be constructed directly from a row of the DataFrame returned by
    ``models.credit_risk.predict.predict_pd()``.
    """

    pd_score: float
    pd_band: str  # "low" | "medium" | "high"


@dataclass
class DecisionRequest:
    """Full input bundle for the decision engine.

    Parameters
    ----------
    application_id:
        UUID string identifying the loan application.
    fraud_result:
        Output from the fraud detection model.
    credit_result:
        Output from the credit risk model.
    pricing_result:
        Output from the pricing engine.
    loan_amount:
        Requested loan amount in USD.
    loan_term_months:
        Requested loan term (12 / 24 / 36 / 48 / 60 months).
    debt_to_income_ratio:
        Applicant's debt-to-income ratio (0.0 – 0.65).
    num_open_accounts:
        Number of open credit accounts.
    annual_income:
        Gross annual income in USD (optional; used only for loan_terms metadata).
    """

    application_id: str
    fraud_result: FraudResult
    credit_result: CreditResult
    pricing_result: PricingResult
    loan_amount: float
    loan_term_months: int
    debt_to_income_ratio: float
    num_open_accounts: int
    annual_income: Optional[float] = None


@dataclass
class DecisionResult:
    """Full output from the decision engine for a single application.

    Parameters
    ----------
    application_id:
        Echoed from the request for traceability.
    decision:
        Final lending decision: ``"APPROVE"``, ``"REJECT"``, or
        ``"MANUAL_REVIEW"``.
    recommended_rate:
        Annual interest rate (%) to offer; ``None`` for rejections.
    loan_terms:
        Dictionary with structured loan offer details (amount, term,
        rate, estimated monthly payment, expected loss, expected profit).
        Empty dict for rejections.
    reason_codes:
        List of FCRA adverse action codes explaining the decision.
    decision_timestamp:
        UTC timestamp of when the decision was made.
    decision_latency_ms:
        Wall-clock time (ms) from request receipt to decision completion.
    """

    application_id: str
    decision: str
    recommended_rate: Optional[float]
    loan_terms: Dict
    reason_codes: List[str]
    decision_timestamp: datetime
    decision_latency_ms: int
    # GAP-02: override records collected during this decision (empty when no overrides applied)
    override_records: List[Any] = field(default_factory=list)
    # GAP-23: Populated only when decision == DECISION_CONDITIONAL.
    conditional_terms: Optional[ConditionalTerms] = None
    # S4-A: Conditions for conditional approval
    conditions: List[Any] = field(default_factory=list)
    # S4-A: Alternative structures for declined applications
    alternative_structures: List[Any] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _monthly_payment(principal: float, annual_rate: float, term_months: int) -> float:
    """Calculate the fixed monthly instalment using the annuity formula.

    Parameters
    ----------
    principal:
        Loan principal in USD.
    annual_rate:
        Annual interest rate as a percentage (e.g., ``7.5`` for 7.5%).
    term_months:
        Loan term in months.

    Returns
    -------
    float
        Monthly payment in USD, rounded to 2 decimal places.
    """
    monthly_rate = annual_rate / 100 / 12
    if monthly_rate == 0:
        return round(principal / term_months, 2)
    payment = principal * monthly_rate / (1 - (1 + monthly_rate) ** -term_months)
    return round(payment, 2)


def _collect_reason_codes(
    decision: str,
    fraud_result: FraudResult,
    credit_result: CreditResult,
    debt_to_income_ratio: float,
    num_open_accounts: int,
) -> List[str]:
    """Collect applicable FCRA adverse action codes.

    Reason codes are always included for ``REJECT`` and
    ``MANUAL_REVIEW`` decisions. For ``APPROVE`` decisions an empty
    list is returned (no adverse action notice required).

    Parameters
    ----------
    decision:
        The tentative decision string.
    fraud_result, credit_result:
        Model outputs.
    debt_to_income_ratio, num_open_accounts:
        Raw application fields used for supplemental codes.

    Returns
    -------
    List[str]
        Ordered list of applicable adverse action codes.
    """
    if decision == DECISION_APPROVE:
        return []

    codes: List[str] = []

    # Primary reason from the decision path
    if fraud_result.fraud_flag == "reject":
        codes.append("AA02")
    elif fraud_result.fraud_flag == "manual_review":
        codes.append("AA05")
    elif credit_result.pd_score > PD_THRESHOLD_MEDIUM:
        codes.append("AA01")

    # Supplemental reason codes (provide additional context)
    if num_open_accounts < OPEN_ACCOUNTS_MIN:
        codes.append("AA03")
    if debt_to_income_ratio > DTI_HIGH_THRESHOLD:
        codes.append("AA04")

    # De-duplicate whilst preserving order (Python 3.7+ dict trick)
    return list(dict.fromkeys(codes))


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def make_decision(
    request: DecisionRequest,
    *,
    policy_overrides: Optional[Dict[str, Any]] = None,
    # GAP-02: override audit fields — required whenever policy_overrides is non-empty
    override_submitted_by: Optional[str] = None,
    override_approved_by: Optional[str] = None,
    override_justification: Optional[str] = None,
    # GAP-11: set True in simulation/replay contexts — bypasses four-eyes GAP-02 check
    _simulation: bool = False,
) -> DecisionResult:
    """Apply the decision policy and return a ``DecisionResult``.

    Decision tree
    ~~~~~~~~~~~~~
    1. **Fraud reject**      → ``REJECT``        (AA02)
    2. **Fraud review**      → ``MANUAL_REVIEW`` (AA05)
    3. **pd_score < 0.05**   → ``APPROVE``       at base rate
    4. **pd_score ≤ 0.10**   → ``APPROVE``       at risk-priced rate
    5. **pd_score > 0.10**   → ``REJECT``        (AA01)

    Parameters
    ----------
    request:
        Populated :class:`DecisionRequest` instance.
    policy_overrides : dict, optional
        Per-tenant policy cutoff overrides resolved from the Config Registry
        (P2.1).  Supported keys::

            pd_threshold      float  — replaces PD_THRESHOLD_MEDIUM
            pd_threshold_low  float  — replaces PD_THRESHOLD_LOW
            dti_high          float  — replaces DTI_HIGH_THRESHOLD

        Unknown keys are silently ignored so future cutoff additions are
        backwards-compatible.
    _simulation:
        Internal flag for simulation / replay contexts (GAP-11).
        When True, GAP-02 four-eyes validation is skipped;
        no override audit records are generated.
        Must **not** be set True in live production decision paths.

    Returns
    -------
    DecisionResult
        Complete decision with audit fields.
    """
    start_ns = time.perf_counter_ns()

    # P2.1 — Apply per-tenant policy cutoffs when provided
    overrides = policy_overrides or {}

    # GAP-02 — Require four-eyes approval metadata whenever overrides are applied
    # (skipped in simulation context via _simulation=True)
    _override_records: List[Any] = []
    if overrides and not _simulation:
        if (
            override_submitted_by is None
            or override_approved_by is None
            or override_justification is None
            or len(override_justification) < 10
        ):
            raise ValueError(
                "policy_overrides require override_submitted_by, override_approved_by, "
                "and override_justification (min 10 chars)"
            )
        # Four-eyes: submitter != approver
        from compliance.rbac import validate_override_submission
        validate_override_submission(
            submitted_by=override_submitted_by,
            approved_by=override_approved_by,
            justification=override_justification,
        )
        # Build a PolicyOverrideRecord stub for each key so the caller can
        # persist them via audit.override_log.log_override().
        try:
            from audit.override_log import PolicyOverrideRecord
            _approved_at = datetime.now(tz=timezone.utc).isoformat()
            for _k, _v in overrides.items():
                # Determine original value from engine constants
                _original: float
                if _k == "pd_threshold_low":
                    _original = PD_THRESHOLD_LOW
                elif _k == "pd_threshold":
                    _original = PD_THRESHOLD_MEDIUM
                elif _k == "dti_high":
                    _original = DTI_HIGH_THRESHOLD
                else:
                    _original = 0.0
                import uuid as _uuid
                _override_records.append(PolicyOverrideRecord(
                    override_id=str(_uuid.uuid4()),
                    decision_id=request.application_id,
                    tenant_id="",  # filled in by the API layer which knows the tenant
                    override_type=_k,
                    original_value=_original,
                    override_value=float(_v),
                    justification=override_justification,
                    submitted_by=override_submitted_by,
                    approved_by=override_approved_by,
                    approved_at=_approved_at,
                ))
        except ImportError:
            pass  # audit module unavailable in minimal test setups
    _pd_low    = float(overrides.get("pd_threshold_low", PD_THRESHOLD_LOW))
    _pd_medium = float(overrides.get("pd_threshold",     PD_THRESHOLD_MEDIUM))

    # Per-product escalation bands override the generic thresholds (S6-A)
    _product_type = getattr(request, "product_type", None) or overrides.get("product_type")
    if _product_type and "pd_threshold_low" not in overrides and "pd_threshold" not in overrides:
        _esc_low, _esc_high = _load_escalation_bands(_product_type)
        _pd_low    = _esc_low
        _pd_medium = _esc_high

    fraud = request.fraud_result
    credit = request.credit_result
    pricing = request.pricing_result

    # ------------------------------------------------------------------
    # Step 1 — Apply decision tree
    # ------------------------------------------------------------------
    if fraud.fraud_flag == "reject":
        decision = DECISION_REJECT

    elif fraud.fraud_flag == "manual_review":
        decision = DECISION_MANUAL_REVIEW

    elif credit.pd_score < _pd_low:
        decision = DECISION_APPROVE

    elif credit.pd_score <= _pd_medium:
        # Within escalation band → MANUAL_REVIEW; generic path → APPROVE
        if _product_type:
            decision = DECISION_MANUAL_REVIEW
        else:
            decision = DECISION_APPROVE

    else:
        decision = DECISION_REJECT

    # ------------------------------------------------------------------
    # S4-A — Post-decision Conditional Approval check
    # ------------------------------------------------------------------
    # If pd_score <= 0.10 (risk-acceptable) but soft conditions fire,
    # downgrade APPROVE to CONDITIONAL.
    # Fraud/MANUAL_REVIEW decisions are never overridden.
    # ------------------------------------------------------------------
    if decision == DECISION_APPROVE and credit.pd_score <= 0.10:
        _features = getattr(request, "features", {}) or {}
        _income_verified = bool(_features.get("income_verified", True))
        _dti = request.debt_to_income_ratio
        _num_open = request.num_open_accounts
        _collateral_coverage = float(_features.get("collateral_coverage_ratio", 0.0))
        _has_collateral = bool(_features.get("collateral_value"))

        _early_conditions: List[Any] = []
        try:
            from decision_engine.conditions import Condition
            if not _income_verified:
                _early_conditions.append(Condition(
                    condition_type="INCOME_VERIFICATION_REQUIRED",
                    description="Income has not been verified. Verification required before funding.",
                ))
            if 0.43 <= _dti <= 0.50:
                _early_conditions.append(Condition(
                    condition_type="REDUCED_LIMIT",
                    description=f"DTI of {_dti:.2f} is elevated. Reduced credit limit recommended.",
                ))
            if _has_collateral and 0 < _collateral_coverage < 1.0:
                _early_conditions.append(Condition(
                    condition_type="COLLATERAL_REQUIRED",
                    description=(
                        f"Collateral coverage ratio of {_collateral_coverage:.2f} is below 1.0. "
                        "Additional collateral or appraisal required."
                    ),
                    min_coverage_ratio=1.0,
                ))
            if _num_open < 3:
                _early_conditions.append(Condition(
                    condition_type="ADDITIONAL_DOCUMENTATION",
                    description="Thin credit file (fewer than 3 open trades). Additional documentation required.",
                    doc_types=["bank_statements", "alternative_credit_data"],
                ))
        except ImportError:
            pass

        if _early_conditions:
            decision = DECISION_CONDITIONAL

    # ------------------------------------------------------------------
    # Step 2 — Build loan terms (only meaningful for APPROVE)
    # ------------------------------------------------------------------
    if decision == DECISION_APPROVE:
        rate = pricing.recommended_rate
        monthly = _monthly_payment(request.loan_amount, rate, request.loan_term_months)
        loan_terms: Dict = {
            "loan_amount": request.loan_amount,
            "loan_term_months": request.loan_term_months,
            "annual_rate_pct": rate,
            "monthly_payment": monthly,
            "expected_loss": pricing.expected_loss,
            "expected_profit": pricing.expected_profit,
            "profitability_flag": pricing.profitability_flag,
        }
        recommended_rate: Optional[float] = rate
    else:
        loan_terms = {}
        recommended_rate = None

    # ------------------------------------------------------------------
    # Step 3 — Collect reason codes
    # ------------------------------------------------------------------
    reason_codes = _collect_reason_codes(
        decision=decision,
        fraud_result=fraud,
        credit_result=credit,
        debt_to_income_ratio=request.debt_to_income_ratio,
        num_open_accounts=request.num_open_accounts,
    )

    # ------------------------------------------------------------------
    # Step 4 — Compute latency and timestamp
    # ------------------------------------------------------------------
    elapsed_ms = int((time.perf_counter_ns() - start_ns) / 1_000_000)
    decision_timestamp = datetime.now(tz=timezone.utc)

    # S4-A — Generate alternative structures for pure rejections
    _alt_structures: List[Any] = []
    if decision == DECISION_REJECT:
        try:
            from decision_engine.alternative_structures import generate_alternatives
            _alt_structures = generate_alternatives(
                request=request,
                pd_score=credit.pd_score,
                decision=decision,
            )
        except Exception as _alt_exc:
            log.warning("Alternative structures generation failed (non-fatal): %s", _alt_exc)

    # S4-A — conditions populated during conditional approval path
    # _early_conditions was built above if decision == CONDITIONAL;
    # fall back to empty list otherwise.
    _conditions: List[Any] = locals().get("_early_conditions", [])

    return DecisionResult(
        application_id=request.application_id,
        decision=decision,
        recommended_rate=recommended_rate,
        loan_terms=loan_terms,
        reason_codes=reason_codes,
        decision_timestamp=decision_timestamp,
        decision_latency_ms=elapsed_ms,
        override_records=_override_records,
        conditions=_conditions,
        alternative_structures=_alt_structures,
    )


# ---------------------------------------------------------------------------
# CLI convenience
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import json
    import uuid

    from models.pricing.engine import PricingConfig, calculate_pricing

    _pricing_cfg = PricingConfig()
    _pricing = calculate_pricing(pd_score=0.03, fraud_flag="continue",
                                 loan_amount=20_000.0, config=_pricing_cfg)

    _req = DecisionRequest(
        application_id=str(uuid.uuid4()),
        fraud_result=FraudResult(fraud_probability=0.1, fraud_flag="continue"),
        credit_result=CreditResult(pd_score=0.03, pd_band="low"),
        pricing_result=_pricing,
        loan_amount=20_000.0,
        loan_term_months=36,
        debt_to_income_ratio=0.25,
        num_open_accounts=5,
        annual_income=75_000.0,
    )

    _result = make_decision(_req)
    print(json.dumps(
        {
            "application_id": _result.application_id,
            "decision": _result.decision,
            "recommended_rate": _result.recommended_rate,
            "loan_terms": _result.loan_terms,
            "reason_codes": _result.reason_codes,
            "decision_timestamp": _result.decision_timestamp.isoformat(),
            "decision_latency_ms": _result.decision_latency_ms,
        },
        indent=2,
    ))
