"""
data_contracts.v1.compliance
==============================
Contracts for regulatory compliance records: Reg B adverse action notices,
HMDA LAR records, Metro 2 credit bureau tradelines, and fair-lending flags.

Consumers
---------
* LucidCredit  — ingests AdverseActionNoticeV1 for compliance Q&A
* AgentHiveHQ  — monitors FairLendingFlagV1 for regulatory alert workflows
* Regulators   — HMDARecordV1 feeds the LAR export; Metro2TradelineV1 feeds
                 the monthly credit bureau file

Regulatory references
---------------------
* ECOA / Reg B — 12 CFR Part 202; adverse action model form C-1
* FCRA         — 15 U.S.C. §1681 et seq.; reason code disclosure
* HMDA / Reg C — 12 CFR Part 1003; LAR filing
* Metro 2      — CDIA credit reporting standard
* UDAAP        — CFPB Supervision and Examination Manual
"""

from __future__ import annotations

from datetime import date, datetime, timezone
from enum import Enum
from typing import List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class ActionTakenV1(str, Enum):
    """HMDA action taken codes."""
    ORIGINATED = "1"
    APPROVED_NOT_ACCEPTED = "2"
    DENIED = "3"
    WITHDRAWN = "4"
    CLOSED_INCOMPLETE = "5"
    PURCHASED = "6"
    PREAPPROVAL_DENIED = "7"
    PREAPPROVAL_APPROVED_NOT_ACCEPTED = "8"


class DenialReasonV1(str, Enum):
    """HMDA denial reason codes (up to 4 per application)."""
    DEBT_TO_INCOME = "1"
    EMPLOYMENT_HISTORY = "2"
    CREDIT_HISTORY = "3"
    COLLATERAL = "4"
    INSUFFICIENT_CASH = "5"
    UNVERIFIABLE_INFORMATION = "6"
    CREDIT_APP_INCOMPLETE = "7"
    MORTGAGE_INSURANCE_DENIED = "8"
    OTHER = "9"


class RaceCodeV1(str, Enum):
    AMERICAN_INDIAN_ALASKA_NATIVE = "1"
    ASIAN = "2"
    BLACK_AFRICAN_AMERICAN = "3"
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER = "4"
    WHITE = "5"
    INFO_NOT_PROVIDED = "6"
    NOT_APPLICABLE = "7"


class EthnicityCodeV1(str, Enum):
    HISPANIC_LATINO = "1"
    NOT_HISPANIC = "2"
    INFO_NOT_PROVIDED = "3"
    NOT_APPLICABLE = "4"


class SexCodeV1(str, Enum):
    MALE = "1"
    FEMALE = "2"
    INFO_NOT_PROVIDED = "3"
    NOT_APPLICABLE = "4"


class Metro2AccountStatusV1(str, Enum):
    CURRENT = "11"
    DELINQUENT_30 = "71"
    DELINQUENT_60 = "78"
    DELINQUENT_90 = "80"
    DELINQUENT_120 = "82"
    CHARGE_OFF = "97"
    PAID_OFF = "13"
    CLOSED = "05"


class DisparateImpactStatusV1(str, Enum):
    PASS = "pass"             # Approval rate ratio ≥ 0.80 (4/5 rule)
    WARN = "warn"             # 0.70 ≤ ratio < 0.80
    FAIL = "fail"             # ratio < 0.70 (potential ECOA/UDAAP violation)
    INSUFFICIENT_DATA = "insufficient_data"  # < 30 observations in control group


# ---------------------------------------------------------------------------
# Base
# ---------------------------------------------------------------------------


class _ContractBaseV1(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    schema_version: Literal["1.0.0"] = "1.0.0"
    contract_name: str = Field(...)


# ---------------------------------------------------------------------------
# AdverseActionNoticeV1 — Reg B / FCRA adverse action disclosure
# ---------------------------------------------------------------------------


class AdverseActionNoticeV1(_ContractBaseV1):
    """
    FCRA/Reg B adverse action notice for a denied or counter-offered application.

    Generated by ``compliance/adverse_action_generator.py`` and stored in
    ``compliance/adverse_action_store.py``.  Must be delivered to the applicant
    within 30 days of the decision per Reg B §202.9.

    PII fields are tagged — consumers must redact before warehousing.
    """

    contract_name: Literal["AdverseActionNoticeV1"] = "AdverseActionNoticeV1"

    notice_id: str = Field(..., description="Unique notice identifier (UUID).")
    application_id: str
    tenant_id: str

    # Decision context
    decision_date: date
    action_type: Literal["denial", "counter_offer", "incomplete"]

    # Reg B reason codes (1–4 principal reasons)
    reason_codes: List[str] = Field(
        ..., min_length=1, max_length=4,
        description="FCRA principal reason codes from compliance/adverse_action.py "
                    "(AA01-AA06 or SHAP_* codes).",
    )
    reason_texts: List[str] = Field(
        ..., min_length=1, max_length=4,
        description="Human-readable disclosure text for each reason code.",
    )

    # Credit score disclosure (FCRA §615(a))
    credit_score_used: Optional[float] = Field(
        None, ge=300.0, le=850.0,
        json_schema_extra={"pii": True},
        description="Credit score used in the decision, if any.",
    )
    credit_score_range_low: Optional[float] = Field(None, ge=300.0)
    credit_score_range_high: Optional[float] = Field(None, le=850.0)
    credit_score_model_name: Optional[str] = None

    # Delivery metadata
    delivery_method: Literal["email", "mail", "in_app", "api"] = "api"
    delivery_deadline: date = Field(
        ...,
        description="Reg B 30-day delivery deadline from decision_date.",
    )
    delivered_at: Optional[datetime] = None

    # Full notice text
    notice_text: str = Field(
        ...,
        description="Full Reg B model form C-1 notice text as rendered to the applicant.",
    )

    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# HMDARecordV1 — HMDA Loan Application Register (LAR) entry
# ---------------------------------------------------------------------------


class HMDARecordV1(_ContractBaseV1):
    """
    HMDA Loan Application Register (LAR) record per Reg C 12 CFR Part 1003.

    One record per loan application. Submitted annually to the FFIEC / CFPB.
    Fields follow the 2018+ HMDA data spec.

    NOTE: Many fields carry demographic data that is strictly regulated.
    The ``pii`` annotation is set on fields that must be suppressed in
    non-regulatory exports.
    """

    contract_name: Literal["HMDARecordV1"] = "HMDARecordV1"

    uli: str = Field(
        ...,
        description="Universal Loan Identifier (ULI) — 23–45 character string.",
    )
    application_id: str
    tenant_id: str
    lei: str = Field(..., description="Legal Entity Identifier of the financial institution.")

    # Loan characteristics
    loan_type: Literal["1", "2", "3", "4"] = Field(
        ...,
        description="1=Conventional, 2=FHA, 3=VA, 4=RHS/FSA.",
    )
    loan_purpose: Literal["1", "2", "31", "32", "4", "5"] = Field(
        ...,
        description="1=Purchase, 2=Home improvement, 31=Refinancing, 32=Cash-out refi, 4=Other, 5=N/A.",
    )
    lien_status: Literal["1", "2"] = Field(..., description="1=First lien, 2=Subordinate lien.")
    loan_amount: float = Field(..., ge=0, description="Loan amount in USD (thousands for reporting).")

    # Property
    property_type: Optional[Literal["1", "2", "3"]] = Field(
        None,
        description="1=Single family, 2=Manufactured, 3=Multi-family.",
    )
    occupancy_type: Optional[Literal["1", "2", "3"]] = Field(
        None,
        description="1=Principal residence, 2=Second home, 3=Investment.",
    )
    census_tract: Optional[str] = Field(None, description="11-digit FIPS census tract.")
    msa_md: Optional[str] = Field(None, description="MSA/MD code.")
    state_code: Optional[str] = Field(None, max_length=2)
    county_code: Optional[str] = Field(None, max_length=5)

    # Action
    action_taken: ActionTakenV1
    action_taken_date: date
    denial_reasons: List[DenialReasonV1] = Field(default_factory=list, max_length=4)

    # Applicant demographics (PII)
    applicant_race: List[RaceCodeV1] = Field(
        default_factory=list, max_length=5,
        json_schema_extra={"pii": True},
    )
    applicant_ethnicity: Optional[EthnicityCodeV1] = Field(
        None, json_schema_extra={"pii": True},
    )
    applicant_sex: Optional[SexCodeV1] = Field(
        None, json_schema_extra={"pii": True},
    )
    applicant_age: Optional[int] = Field(
        None, ge=18, json_schema_extra={"pii": True},
    )
    applicant_income: Optional[float] = Field(
        None, ge=0,
        description="Gross annual income in USD (thousands for HMDA reporting).",
    )

    # Credit risk
    rate_spread: Optional[float] = Field(
        None,
        description="Difference between APR and APOR (Average Prime Offer Rate) "
                    "in percentage points. Required if rate_spread ≥ 1.5% (first lien) "
                    "or 3.5% (subordinate).",
    )
    hoepa_status: Literal["1", "2", "3"] = Field(
        "3",
        description="1=HOEPA loan, 2=Not HOEPA, 3=N/A.",
    )
    total_loan_costs: Optional[float] = Field(None, ge=0, description="Total loan costs in USD.")
    origination_charges: Optional[float] = Field(None, ge=0)
    discount_points: Optional[float] = Field(None, ge=0)
    lender_credits: Optional[float] = None
    interest_rate: Optional[float] = Field(None, ge=0.0)
    prepayment_penalty_term: Optional[int] = Field(None, ge=0)
    debt_to_income_ratio: Optional[str] = Field(None, description="DTI ratio string or 'Exempt'.")
    combined_ltv: Optional[float] = Field(None, ge=0.0)
    loan_term: Optional[int] = Field(None, ge=0, description="Loan term in months.")
    intro_rate_period: Optional[int] = Field(None, ge=0)
    balloon_payment: Literal["1", "2", "1111"] = Field("2", description="1=Yes, 2=No, 1111=Exempt.")
    interest_only_payments: Literal["1", "2", "1111"] = Field("2")
    negative_amortization: Literal["1", "2", "1111"] = Field("2")
    other_non_amortizing: Literal["1", "2", "1111"] = Field("2")
    property_value: Optional[float] = Field(None, ge=0)
    manufactured_home_secured_property_type: Optional[str] = None
    manufactured_home_land_property_interest: Optional[str] = None
    total_units: Optional[int] = Field(None, ge=1)

    # AUS
    aus_name: Optional[str] = None
    aus_result: Optional[str] = None

    # Reversionary
    submission_id: Optional[str] = None
    lar_sequence_number: Optional[int] = None
    reported_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# Metro2TradelineV1 — credit bureau tradeline (CDIA Metro 2 format)
# ---------------------------------------------------------------------------


class Metro2TradelineV1(_ContractBaseV1):
    """
    Monthly credit bureau tradeline in CDIA Metro 2 format.

    Submitted to Equifax, Experian, TransUnion, and Innovis monthly.
    Consumers (ThinFile, LucidCredit) use this to understand what payment
    history was reported for a given applicant.

    PII fields are annotated — the tradeline must only be transmitted over
    encrypted channels and never stored in logs.
    """

    contract_name: Literal["Metro2TradelineV1"] = "Metro2TradelineV1"

    # Segment identifiers
    portfolio_type: Literal["C", "I", "M", "O", "R"] = Field(
        ...,
        description="C=Credit card, I=Installment, M=Mortgage, O=Open, R=Revolving.",
    )
    account_number: str = Field(
        ...,
        json_schema_extra={"pii": True},
        description="Masked account number — last 4 digits only in non-bureau exports.",
    )
    tenant_id: str

    # Date fields
    date_opened: date
    date_of_first_delinquency: Optional[date] = None
    date_of_last_payment: Optional[date] = None
    date_closed: Optional[date] = None
    date_of_account_information: date = Field(
        ...,
        description="As-of date for this tradeline submission.",
    )

    # Balance
    highest_credit: Optional[float] = Field(None, ge=0)
    credit_limit: Optional[float] = Field(None, ge=0)
    current_balance: Optional[float] = Field(None, ge=0)
    amount_past_due: Optional[float] = Field(None, ge=0)

    # Status
    account_status: Metro2AccountStatusV1
    payment_rating: Optional[str] = Field(
        None,
        description="Metro 2 payment rating code (0=current, 1=30dpd, 2=60dpd, …).",
    )
    payment_history_profile: Optional[str] = Field(
        None, max_length=24,
        description="24-month payment history string (0=current, 1-6=dpd buckets, B=no hist).",
    )

    # Subscriber info
    subscriber_name: str
    subscriber_code: str

    # Consumer PII (transmitted to bureaus only — not stored in analytics)
    consumer_ssn_last4: Optional[str] = Field(
        None, min_length=4, max_length=4,
        json_schema_extra={"pii": True},
    )
    consumer_dob_year: Optional[int] = Field(
        None, ge=1900, le=2010,
        json_schema_extra={"pii": True},
    )

    reported_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# FairLendingFlagV1 — disparate impact / ECOA monitoring flag
# ---------------------------------------------------------------------------


class FairLendingFlagV1(_ContractBaseV1):
    """
    Fair lending monitoring flag produced by the BISG + disparate impact
    analysis in ``monitoring/fair_lending.py``.

    A FAIL status does NOT automatically constitute an ECOA violation —
    it triggers a manual review workflow in AgentHiveHQ. Only the compliance
    officer may close a FAIL flag.

    Computed monthly or on-demand. The 4/5 (80%) rule is the default test;
    standard error and statistical significance are also reported.
    """

    contract_name: Literal["FairLendingFlagV1"] = "FairLendingFlagV1"

    flag_id: str = Field(..., description="Unique flag identifier (UUID).")
    tenant_id: str
    product_type: str

    # Analysis window
    analysis_period_start: date
    analysis_period_end: date
    n_applications_analyzed: int = Field(..., ge=0)

    # Protected class analysis
    protected_class: str = Field(
        ...,
        description="Protected class dimension: 'race', 'sex', 'ethnicity', 'age_65_plus'.",
    )
    control_group: str = Field(
        ...,
        description="Control group label (e.g. 'White non-Hispanic').",
    )
    protected_group: str = Field(
        ...,
        description="Protected group label (e.g. 'Black non-Hispanic').",
    )

    # Approval rates
    control_approval_rate: float = Field(..., ge=0.0, le=1.0)
    protected_approval_rate: float = Field(..., ge=0.0, le=1.0)
    approval_rate_ratio: float = Field(
        ..., ge=0.0,
        description="protected_approval_rate / control_approval_rate. "
                    "Ratio < 0.80 triggers the 4/5 rule.",
    )
    approval_rate_difference: float = Field(
        ...,
        description="protected_approval_rate − control_approval_rate (signed).",
    )

    # Statistical significance
    p_value: Optional[float] = Field(None, ge=0.0, le=1.0)
    is_statistically_significant: Optional[bool] = None

    # Verdict
    status: DisparateImpactStatusV1
    review_required: bool = Field(
        ...,
        description="True when status is FAIL or WARN with p_value < 0.05.",
    )
    reviewer_notes: Optional[str] = None
    closed_at: Optional[datetime] = None

    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
